# Generated by Django 3.2.1 on 2021-05-06 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0004_game_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 15, 33, 6, 863520)),
        ),
    ]
